# Generated by Django 4.0.3 on 2022-04-11 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='temp',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
    ]
