# примеры API-запросов

# получение датчика
GET http://localhost:8000/api/sensor/1/
Content-Type: application/json

###

# получение датчиков
GET http://localhost:8000/api/sensors/
Content-Type: application/json

###

# создание датчика
POST http://localhost:8000/api/new_sensor/
Content-Type: application/json

{
  "name": "1C",
  "description": "bathroom"
}

###

# обновление датчика
PATCH http://localhost:8000/api/update_sensor/3/
Content-Type: application/json

{
  "description": "Перенес датчик на балкон"
}

###

# добавление измерения
POST http://localhost:8000/api/measurements/
Content-Type: application/json

{
  "sensor_id": 2,
  "temp": 20.3
}

###

# получение информации по измерению
GET http://localhost:8000/api/measure_check/
Content-Type: application/json

###

# получение информации по датчику
GET http://localhost:8000/api/sensor_data/3/
Content-Type: application/json
