# примеры API-запросов

@baseUrl = http://localhost:8000/api/v1
###
# создание продукта
POST http://localhost:8000/api/v1/products/
Content-Type: application/json

{
  "title": "Морковка",
  "description": "Лучшая морковка на рынке"
}

###

# получение продуктов
GET http://localhost:8000/api/v1/products/
Content-Type: application/json

###

# обновление продукта
PATCH http://localhost:8000/api/v1/products/1/
Content-Type: application/json

{
  "description": "Самые сочные и ароматные помидорки"
}

###

# удаление продукта
DELETE {{baseUrl}}/products/1/
Content-Type: application/json

###

# поиск продуктов по названию и описанию
GET http://localhost:8000/api/v1/products/?search=рын
Content-Type: application/json

###

# создание склада
POST http://localhost:8000/api/v1/stocks/
Content-Type: application/json

{
  "address": "Сокол",
  "positions": [
    {
      "product": 2,
      "quantity": 250,
      "price": 120.50
    },
    {
      "product": 3,
      "quantity": 100,
      "price": 180
    }
  ]
}

###

# обновляем записи на складе
PATCH http://localhost:8000/api/v1/stocks/3/
Content-Type: application/json

{
  "positions": [
    {
      "product": 2,
      "quantity": 80,
      "price": 140.80
    },
    {
      "product": 3,
      "quantity": 201,
      "price": 170
    }
  ]
}

###

# поиск складов, где есть определенный продукт по id
GET http://localhost:8000/api/v1/stocks/?products=2
Content-Type: application/json


